name: Build Docker Images (All)

on:
  push:
    branches:
      - main
    paths:
      - 'Docker/*'
      - '.github/workflows/publish.yml'
  #schedule:
  #  - cron: '0 0 * * 0' # Every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list_dockerfiles.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List Dockerfiles
        id: list_dockerfiles
        run: |
          files=$(ls Docker/*.dockerfile | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$files" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.prepare.outputs.matrix) }}
        rust_version:
          - 1.87.0
          - nightly
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          name=$(basename ${{ matrix.dockerfile }} .dockerfile)
          name=$(echo "$name" | tr '_' '-')
          today=$(date +%Y%m%d)
          rust_version=${{ matrix.rust_version }}
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --build-arg RUST_VERSION=${{ matrix.rust_version }} \
            -t ghcr.io/pirafrank/rust:$rust_version-$name-latest \
            -t ghcr.io/pirafrank/rust:$rust_version-$name-$today \
            -f ${{ matrix.dockerfile }} \
            .
